        </td><td width=6 bgcolor="#3D3E46">&nbsp;</td>
</tr>
</table>
<script type="text/javascript" src="<?=COMMON_URL;?>etc/troll.js"></script>
<noscript>
<img src="http://top.2s.ru/cnt?cid=jehy" alt='top.2s.ru' title="Участник RHC's top" border=0 width=1 height=1></noscript>
<img src="/images/dot.gif" width="1px" height="1px" style="display:none">
<?//<iframe style="border:0;width:1px;height:1px;" src="/sys/" width="1px" height="1px"></iframe>
          ?>
</noscript>
</body>
</html>
