<a href='<?= COMMON_URL; ?>index.php?page=user'>Вернуться в систему администрирования</a><br>
<span class="larger">Внимание!</span><p>
    Ставьте к себе на сайт код баннера того стандарта, банер которого вы загрузили в систему (если вы загрузили
    несколько типов банеров, то и код надо ставить для этих типов).</p><p>
    Имеется в виду, что если вы, например, закачали банеры размера 88*31 и 468*60, то следует поставить два кода для
    банеров 88*31 и 468*60, но никак не для 100*100, например:).</p>
<br>Код баннера стандарта 88*31:<br>
<textarea rows="8" cols="60">
    <script language="JavaScript">
        d = new Date();
        var m = d.getTime();
        m = m + '&url=';
        m = m + self.location;
        var a = '<a title="Каталог фэнтези сайтов и банерообменная система Палантир" href="<?=COMMON_URL;?>index.php?from=<?=$site_id;?>&rand=' + m + '" target="_blank"><img alt="Каталог фэнтези сайтов и банерообменная система Палантир" src="<?=COMMON_URL;?>showban2.php?type=1&from=<?=$site_id;?>&rand=' + m;
        a = a + '" width="88" height="31" border="0"></a>';
        document.write(a);
    </script>
    <noscript><a title="Каталог фэнтези сайтов и банерообменная система Палантир"
                 href="<?= COMMON_URL; ?>index.php?from=<?= $site_id; ?>" target="_blank"><img
                alt="Каталог фэнтези сайтов и банерообменная система Палантир"
                src="<?= COMMON_URL; ?>showban2.php?type=1&from=<?= $site_id; ?>" width="88" height="31" border="0"></a>
    </noscript>
</textarea><br><br>

Код баннера стандарта 100*100:<br>
<textarea rows="8" cols="60"><a title="Каталог фэнтези сайтов и банерообменная система Палантир"
                                href="<?= COMMON_URL; ?>index.php?from=<?= $site_id; ?>">
        <script language="JavaScript">
            d = new Date();
            var m = d.getTime();
            m = m + '&url=';
            m = m + self.location;
            var a = '<a href="<?=COMMON_URL;?>index.php?from=<?=$site_id;?>&rand=' + m + '" target="_blank"><img alt="Каталог фэнтези сайтов и банерообменная система Палантир" src="<?=COMMON_URL;?>showban2.php?type=2&from=<?=$site_id;?>&rand=' + m;
            a = a + '" width="100" height="100" border="0"></a>';
            document.write(a);
        </script>
        <noscript><a title="Каталог фэнтези сайтов и банерообменная система Палантир"
                     href="<?= COMMON_URL; ?>index.php?from=<?= $site_id; ?>" target="_blank"><img
                    alt="Каталог фэнтези сайтов и банерообменная система Палантир"
                    src="<?= COMMON_URL; ?>showban2.php?type=2&from=<?= $site_id; ?>" width="100" height="100"
                    border="0"></a></noscript>
</textarea><br><br>

Код баннера стандарта 468*60:<br>
<textarea rows="8" cols="60"><a title="Каталог фэнтези сайтов и банерообменная система Палантир"
                                href="<?= COMMON_URL; ?>index.php?from=<?= $site_id; ?>">
        <script language="JavaScript">
            d = new Date();
            var m = d.getTime();
            m = m + '&url=';
            m = m + self.location;
            var a = '<a href="<?=COMMON_URL;?>index.php?from=<?=$site_id;?>&rand=' + m + '" target="_blank"><img alt="Каталог фэнтези сайтов и банерообменная система Палантир" src="<?=COMMON_URL;?>showban2.php?type=3&from=<?=$site_id;?>&rand=' + m;
            a = a + '" width="468" height="60" border="0"></a>';
            document.write(a);
        </script>
        <noscript><a title="Каталог фэнтези сайтов и банерообменная система Палантир"
                     href="<?= COMMON_URL; ?>index.php?from=<?= $site_id; ?>" target="_blank"><img
                    alt="Каталог фэнтези сайтов и банерообменная система Палантир"
                    src="<?= COMMON_URL; ?>showban2.php?type=3&from=<?= $site_id; ?>" width="468" height="60"
                    border="0"></a></noscript>
</textarea>

<br><br>
P.S. Кстати говоря, нам будет очень приятно, если где-нибудь в разделе "ссылки", "друзья" и т.д. вы поставите на нас текстовую ссылку. По нажатию на неё пользователь попадёт на страницу, на которой у нас описан ваш сайт. Код ссылки:
<textarea readonly cols="80" rows="2"><a href='<?= COMMON_URL; ?>index.php?from=<?= $site_id; ?>' title="палантир"
                                         target='_blank'>Каталог фэнтези сайтов Палантир</a></textarea>
<br><br>
P.P.S. И ещё - если вы хотите как-то заработать на своём сайте, или хотя бы его окупить, рекомендую использовать
<br><a target="_blank" href="http://www.sape.ru/r.f6054dfcc2.php"><img src="http://img.sape.ru/bn/3.gif"
                                                                       border="0"/></a><br>
<a href='index.php?page=user'>Вернуться в систему администрирования</a><br>